### PR TITLE
Bump thread_local and revision number

### PR DESCRIPTION
**Pull request by nipunn1313**

### CODE REVIEW

**Comment by dpc** [comment]
Thanks!

**Comment by nipunn1313** [comment]
Thank you! Would be amazing if you could push this new version out to crates.io

**Comment by nipunn1313** [comment]
If you don't want to make the requirement so strict, you could change to
`thread_local = ">=0.2.6, <0.4"` which would match both (and everything up to 0.4.0 which we're not sure about yet. Up to you. The bump was 6 months ago for language compatibility, so it's probably not too important to keep it working backwards that far, but you know your users better than me! I'm just rooting for support for 0.3.2 dependency.

**Comment by dpc** [comment]
It's an internal depedency. Even is users need to use a previous version of `thread_local` for their own needs, there can be two coexisting ones, so I see no point in not having it as recent as possible.

**Comment by nipunn1313** [comment]
Hey @dpc can you send this (version 1.2.1) out to crates.io?

**Comment by dpc** [comment]
Done.

**Pull request merged**
